### ISSUE TITLE
Socket 创建失败

### ISSUE THREAD

**Issue by itldg** [chenxuuu/llcom#109]
## 描述一下这个bug / Describe the bug
```
[2023/02/11 16:11:56.119]🚀 public socket server: 📢 Server is creating...
[2023/02/11 16:11:56.262]🚀 public socket server: 📢 Create failed
```

## 复现步骤 / To Reproduce
创建TCP和其他的

## 预期的行为 / Expected behavior
正常创建

## 截图 / Screenshots
![image](https://user-images.githubusercontent.com/13432299/218247886-4957c8f9-e123-4d41-bc3b-0e90f6bd4832.png)

## 日志 / Logs
无

## 系统信息 / Desktop (please complete the following information):
无

## 其他备注信息 / Additional context
无

**Comment by itldg** [comment]
如果将代码中的
```csharp
       public WebSocket ws = new WebSocket("wss://netlab.luatos.com/ws/netlab");
       public WebSocket wsV6 = new WebSocket("wss://netlab.luatos.org/ws/netlab");
```
调整为
```csharp
      public WebSocket ws = new WebSocket("ws://netlab.luatos.com/ws/netlab");
      public WebSocket wsV6 = new WebSocket("ws://netlab.luatos.org/ws/netlab");
```
可以暂时解决问题

**Comment by chenxuuu** [comment]
经测试，https://netlab.luatos.org的可以正常连接，另一个不能，原因不明

另外这功能和工具本身没有什么关联，只是用到了这两个网站而已

**Comment by itldg** [comment]
> 经测试，https://netlab.luatos.org 的可以正常连接，另一个不能，原因不明
> 
> 另外这功能和工具本身没有什么关联，只是用到了这两个网站而已

我测试https://netlab.luatos.org 网页创建正常,llcom创建错误,断点测试

在发送创建消息时,socket连接未成功

发送消息会触发error,错误提示`An error has occurred in sending data.`

**Comment by chenxuuu** [comment]
![图片](https://user-images.githubusercontent.com/10357394/218250519-07b61c21-0a1d-4855-8eea-fed9d1f19bb6.png)

fixed
