### ISSUE TITLE
希望添加接受数据解析波形图显示功能

### ISSUE THREAD

**Issue by Dozingfiretruck** [chenxuuu/llcom#113]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
希望添加接受数据解析波形图显示功能，类似
![image](https://user-images.githubusercontent.com/24759100/221886722-440608e3-0b50-4bef-8f8b-cbf7b166aa64.png)

**Comment by chenxuuu** [comment]
已有，请仔细查看设置页自带的数据接收脚本，与小工具页面
