### ISSUE TITLE
希望可以在工具使用时候删除log

### ISSUE THREAD

**Issue by KleinPan** [chenxuuu/llcom#114]
## 描述一下这个bug / Describe the bug
希望可以在工具使用时候删除log，解除文件占用。
现在是每天一个文件，不方便给别人发送

## 复现步骤 / To Reproduce
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:

## 预期的行为 / Expected behavior
希望log可以另存为。可以设置另存为的范围。
举例log生成以当次打开时候到关闭为一个周期。

**Comment by chenxuuu** [comment]
发给别人，只发exe即可

**Comment by KleinPan** [comment]
发log给别人看呢，不是发工具

**Comment by chenxuuu** [comment]
那就发log
