### ISSUE TITLE
socket客户端增加TLS选项

### ISSUE THREAD

**Issue by yuxiao** [chenxuuu/llcom#125]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
无法测试与服务器的TLS连接

## 描述您想要的解决方案 / Describe the solution you'd like
小工具里面“socket客户端”协议选项里面增加TLS选项

## 描述您考虑过的替代方案 / Describe alternatives you've considered
无

## 其他备注信息
无

**Comment by chenxuuu** [comment]
有测试服务器吗？  
需要支持自定义证书吗？  
单向验证还是双向验证？  
双向验证的话有可以用来测试的服务器吗？

**Comment by yuxiao** [comment]
暂没有自定义证书的需求，不过支持更好（跟MQTT支持TLS选项一样的）
测试服务器：tcpbin.com 端口：4243
用法见https://tcpbin.com

**Comment by yuxiao** [comment]
网上找到一个类似功能的工具 https://www.cnblogs.com/guogangj/p/5182129.html

**Comment by chenxuuu** [comment]
![图片](https://github.com/chenxuuu/llcom/assets/10357394/a8dc65f6-2487-4843-b189-421b87bb3464)

done
