### ISSUE TITLE
能否搞个深色模式？

### ISSUE THREAD

**Issue by Atomseek** [chenxuuu/llcom#127]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
看了很多软件，特别是功能很多的那些上古软件，都感觉有丶丑。群主这个风格挺简约的，要是有个深色模式就好了

## 描述您想要的解决方案 / Describe the solution you'd like
可以根据系统跟随改变主题色

## 描述您考虑过的替代方案 / Describe alternatives you've considered
无

## 其他备注信息
无

**Comment by chenxuuu** [comment]
重构后可能会添加该功能

**Comment by chenxuuu** [comment]
等新版本上面再加吧，目前的版本太难改了
