### ISSUE TITLE
增加自定义串口波特率设置数值的显示

### ISSUE THREAD

**Issue by MyZQL** [chenxuuu/llcom#132]
## 描述一下这个bug / Describe the bug
请使用简介并详细的语句，来描述这个bug。 / A clear and concise description of what the bug is.
自定义串口波特率设置的数值没有显示，时间长容易忘记自己设的值，建议增加显示自定义波特率数值的功能。
## 复现步骤 / To Reproduce
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:

## 预期的行为 / Expected behavior
清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.

## 截图 / Screenshots
如果需要，请放上你的截图。 / If applicable, add screenshots to help explain your problem.

## 日志 / Logs
`更多设置`--`打开串口收发日志目录`，可以看到日志 / Upload your log files.

## 系统信息 / Desktop (please complete the following information):
 - 如果可以，可以附加配置文件内容（`更多设置`--`打开串口收发日志目录`--切换到上一级目录--`settings.json`文件）

**Comment by chenxuuu** [comment]
没看懂，重新描述下
