### ISSUE TITLE
串口列表为空

### ISSUE THREAD

**Issue by yuanbi** [chenxuuu/llcom#140]
## 描述一下这个bug / Describe the bug
串口列表为空

## 复现步骤 / To Reproduce
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:
当在Windows设备管理器中可以看到串口，且串口没有被占用时
无论是管理员权限打开llcom，还是正常打开llcom，串口列表均为空

## 预期的行为 / Expected behavior
清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.

## 截图 / Screenshots
![image](https://github.com/chenxuuu/llcom/assets/26222589/67ff69cd-a810-43dc-b935-cd2303a474c1)

## 日志 / Logs
无

## 系统信息 / Desktop (please complete the following information):
 - OS: Windows 10 企业版 LTSC
 - Version 21H2, 19044.3086
 - 设置内容为默认，打开后串口一直为空，没有进行任何额外操作

## 其他备注信息 / Additional context
串口监听中可以看到我的串口
![image](https://github.com/chenxuuu/llcom/assets/26222589/3cc31983-ca36-48f4-8a50-064ddad80fe5)

**Comment by chenxuuu** [comment]
如何复现？

**Comment by renyiwenfighting** [comment]
+1
