### ISSUE TITLE
是否方便提供一个有串口监听功能的版本？

### ISSUE THREAD

**Issue by janes-l** [chenxuuu/llcom#142]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

下载项目后捣鼓了半天，可能因为环境问题还是没跑起来

### 描述您想要的解决方案 / Describe the solution you'd like

带有串口监听功能的版本

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

带有串口监听功能的版本

**Comment by chenxuuu** [comment]
群里有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月4日(周五) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 是否方便提供一个有串口监听功能的版本？ (Issue #142)




 
您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
 
下载项目后捣鼓了半天，可能因为环境问题还是没跑起来
 
描述您想要的解决方案 / Describe the solution you'd like
 
带有串口监听功能的版本
 
描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way
 
带有串口监听功能的版本
 
其他备注信息或截图 / Add any other context or screenshots about the feature request here
 
No response

**Comment by janes-l** [comment]
申请入群了
