### ISSUE TITLE
lua自动化的功能很棒，能否开发一个串口多开的功能，同时对多个串口自动化操作

### ISSUE THREAD

**Issue by blazeccctttyyy** [chenxuuu/llcom#144]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

目前只能对一个串口进行自动化测试

### 描述您想要的解决方案 / Describe the solution you'd like

比如连接了n个串口，则可以都打开，通过脚本对各个串口来的数据进行处理

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

无

**Comment by illusionkiller** [comment]
同求大佬能够支持多串口实例操作，刚才试了一下多个软件打开虽然能实现类似的效果，但还是稍显麻烦

**Comment by chenxuuu** [comment]
新版本（Next版本）会加上这个功能
