### ISSUE TITLE
是不是有必要增加一个定时发送功能？

### ISSUE THREAD

**Issue by zdodo55** [chenxuuu/llcom#145]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

串口定时发送的功能是非常实用的！

### 描述您想要的解决方案 / Describe the solution you'd like

--

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

--

**Comment by chenxuuu** [comment]
lua代码即可实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月9日(周一) 下午5:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 是不是有必要增加一个定时发送功能？ (Issue #145)




 
您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
 
串口定时发送的功能是非常实用的！
 
描述您想要的解决方案 / Describe the solution you'd like
 
--
 
描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way
 
--
 
其他备注信息或截图 / Add any other context or screenshots about the feature request here
 
No response

**Comment by zdodo55** [comment]
> lua代码即可实现
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月9日(周一) 下午5:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [chenxuuu/llcom] 是不是有必要增加一个定时发送功能？ (Issue #145) 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe. 串口定时发送的功能是非常实用的！ 描述您想要的解决方案 / Describe the solution you'd like
> -- 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way
> -- 其他备注信息或截图 / Add any other context or screenshots about the feature request here No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

lua代码实现当然没问题，但是lua主要还是应对复杂的功能，如自动测试之类的，
而定时发送这种简单功能就不用劳烦lua了吧？！如同“发末尾加回车换行”这种打个√的功能，简单又快捷，多好！

**Comment by chenxuuu** [comment]
未提供解决方案
