### ISSUE TITLE
Lua tcp-server回调函数bug

### ISSUE THREAD

**Issue by baishe** [chenxuuu/llcom#146]
![_20231011141234](https://github.com/chenxuuu/llcom/assets/56203948/b615063a-94bf-4013-890d-ae963329682c)

![_20231011141404](https://github.com/chenxuuu/llcom/assets/56203948/0a9efb3f-a97d-4540-96ab-365358267509)

**Comment by chenxuuu** [comment]
```lua
-- socket-client，对应 socket客户端 选项卡
apiSetCb("socket-client",function (data)
  log.info("socket-client received", data)
end)
```
