### ISSUE TITLE
默认fromHex()脚本，会吞掉显示界面HEX格式的部分ASCII字符0x20,0x0D,0x0A等

### ISSUE THREAD

**Issue by qq19538** [chenxuuu/llcom#159]
### 描述一下这个bug / Describe the bug

![image](https://github.com/chenxuuu/llcom/assets/163114121/bd5f1029-4149-4dbe-be96-fc0d1f68279f)
显示界面，把0x20 以及0x0A都吞掉了，猜测应该是ASCII中0x20表示空格，0x0A表示换行，HEX显示时，显示界面程序没有把字符做替换。

### 复现步骤 / To Reproduce

更改编码格式不能避免这个显示吞字符的问题。

### 预期的行为 / Expected behavior

![image](https://github.com/chenxuuu/llcom/assets/163114121/ec9b079a-8956-4e21-9d28-d46d49cc8fea)
实际LOG是这样的

### 系统 / System

WIN10

### 软件版本 / Version

1.1.3.3

### 验证

- [X] 检查该问题是否已被提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qq19538** [comment]
[log20240313.txt](https://github.com/chenxuuu/llcom/files/14586483/log20240313.txt)
日志文件如上

**Comment by qq19538** [comment]
![image](https://github.com/chenxuuu/llcom/assets/163114121/0d873979-5697-4a84-9e31-4a46a8ef5550)
![image](https://github.com/chenxuuu/llcom/assets/163114121/4f59a167-3f7c-4200-a6b9-fd62cb30d3f1)
验证出问题在哪里，默认的脚本使用了fromHex()函数，这个函数应该会替换0x20以及0x0A这类的ASCII码。

**Comment by chenxuuu** [comment]
软件默认脚本不会有任何处理：
https://github.com/chenxuuu/llcom/blob/master/llcom/DefaultFiles/user_script_recv_convert/default.lua
https://github.com/chenxuuu/llcom/blob/master/llcom/Model/Settings.cs#L29

fromhex不要乱用，这是用来把hex转成bin的函数
