### ISSUE TITLE
回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。    在 llcom.LuaEnv.LuaRunEnv.runTigger()

### ISSUE THREAD

**Issue by psuxaog** [chenxuuu/llcom#165]
### 描述一下这个bug / Describe the bug

我在以9600波特率接收非字符串数据”FD 0F 00 00 00 00 00 00 25 FB 00 10 00 00 00 00 06 30 FE“时会时不时报出以下错误
[20:34:08:9734]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
以下是我的LUA代码，当只有uartReceive=function(data) end时也有该问题
``` Lua
uartReceive = function (data)  
	
    --log.info("收到的数据转成HEX是：",data:toHex()) --打印接收的数据的HEX字符串到lua环境  
    local sum = 0    
    for i = 3, 17 do    
        sum = sum + data:byte(i)  
    end    
    sum = sum & 0xFF - 1
    --log.info(string.format("sum:%d, checksum:%d",sum,data:byte(17)))
    if sum == data:byte(18) then    
    	local current,motorVoltage,speed,batVoltage,chargVoltage,chargCurrent,duty  
    	current = data:byte(3)*256+data:byte(4)  
    	motorVoltage = data:byte(5)*256+data:byte(6)  
    	speed = data:byte(7)*256+data:byte(8)  
    	batVoltage = data:byte(9)*256+data:byte(10)  
    	chargVoltage=data:byte(11)*256+data:byte(12)  
    	chargCurrent=data:byte(13)*256+data:byte(14)  
    	errCode=data:byte(17)
    	duty=data:byte(15)  
        -- 打印所有的变量  
        log.info(string.format("电流:%d mA, 电机电压:%d mV, 速度:%d RPM, 电池电压:%d mV, 充电电压:%d mV, 充电电流:%d mA, 占空比:%d, 错误码:%d", current, motorVoltage, speed, batVoltage, chargVoltage, chargCurrent, duty,errCode))    
        --log.info("aa")
    end    
end  
```

### 复现步骤 / To Reproduce

接收我描述的二进制数据

### 预期的行为 / Expected behavior

应该能被正确解析

### 截图 / Screenshots

![image](https://github.com/chenxuuu/llcom/assets/46446377/aaeec1d8-a0fd-4150-ada2-97b6d1e3c6dd)

### 日志 / Logs

[20:37:37:4981][I]-[电流:366 mA, 电机电压:5514 mV, 速度:0 RPM, 电池电压:8806 mV, 充电电压:40 mV, 充电电流:24 mA, 占空比:61, 错误码:0]
[20:37:37:7984][I]-[电流:396 mA, 电机电压:5532 mV, 速度:0 RPM, 电池电压:8709 mV, 充电电压:40 mV, 充电电流:0 mA, 占空比:62, 错误码:0]
[20:37:37:8983]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[20:37:37:9982][I]-[电流:335 mA, 电机电压:5477 mV, 速度:0 RPM, 电池电压:9279 mV, 充电电压:32 mV, 充电电流:0 mA, 占空比:57, 错误码:0]
[20:37:38:3981][I]-[电流:396 mA, 电机电压:5502 mV, 速度:0 RPM, 电池电压:9583 mV, 充电电压:40 mV, 充电电流:0 mA, 占空比:56, 错误码:0]
[20:37:38:6981][I]-[电流:396 mA, 电机电压:5520 mV, 速度:0 RPM, 电池电压:9605 mV, 充电电压:40 mV, 充电电流:24 mA, 占空比:56, 错误码:0]
[20:37:38:7990][I]-[电流:366 mA, 电机电压:5520 mV, 速度:0 RPM, 电池电压:9620 mV, 充电电压:40 mV, 充电电流:0 mA, 占空比:55, 错误码:0]
[20:37:38:8977][I]-[电流:396 mA, 电机电压:5520 mV, 速度:0 RPM, 电池电压:9605 mV, 充电电压:40 mV, 充电电流:0 mA, 占空比:56, 错误码:0]
[20:37:38:9976][I]-[电流:396 mA, 电机电压:5532 mV, 速度:0 RPM, 电池电压:9612 mV, 充电电压:40 mV, 充电电流:0 mA, 占空比:55, 错误码:0]
[20:37:39:2976][I]-[电流:335 mA, 电机电压:5416 mV, 速度:0 RPM, 电池电压:9612 mV, 充电电压:40 mV, 充电电流:0 mA, 占空比:56, 错误码:0]
[20:37:39:3964][I]-[电流:0 mA, 电机电压:4050 mV, 速度:0 RPM, 电池电压:9634 mV, 充电电压:32 mV, 充电电流:0 mA, 占空比:0, 错误码:0]
[20:37:39:4954]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()

### 系统 / System

Win10企业版

### 软件版本 / Version

1.1.3.3

### 验证

- [X] 检查该问题是否已被提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by S4FR** [comment]
遇到了相同的问题。我好像不少脚本都会遇到，就是时间一长就会有，我有一个查询的很快的脚本，就会遇到的非常频繁。

报错如下：

[15:29:32:3125][I]-[sys]	core loaded!
[15:29:33:8118]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:29:40:7615]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:29:43:5231]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:29:58:1494]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:30:01:7588]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:30:02:9473]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:30:13:9054]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()
[15:30:22:5202]回调报错：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 llcom.LuaEnv.LuaRunEnv.runTigger()


我的LUA脚本如下：

local captureArray = {
    "\x60\x40", -- 帧头，例如55和A7
}

-- 注册串口接收函数
apiSetCb("uart", function (data)
    sys.publish("UART", data) -- 发布消息
end)

-- 将字符串转换为十六进制表示
local function toHex(str)
    return (str:gsub('.', function (c)
        return string.format('%02X ', string.byte(c))
    end))
end

-- 获取当前时间戳
local function getTime()
    return os.date("%Y-%m-%d %H:%M:%S")
end

-- 新建任务，等待接收到消息再继续运行
sys.taskInit(function()
    while true do
        -- 等待消息，超时1000ms
        local _, data = sys.waitUntil("UART", 1000)
        if data then
            local timestamp = getTime()
            local hexData = toHex(data)

            -- 遍历捕捉数组
            for _, captureStr in ipairs(captureArray) do
                -- 在接收到的数据中查找完全匹配的字符串
                local matchPos = data:find(captureStr, 1, true)
                if matchPos then
                    local capturedData = data:sub(matchPos, matchPos + #captureStr - 1)
                    print("Timestamp:", timestamp)
                    print("Matched data (hex):", toHex(capturedData))
                    print("Matched at position:", matchPos)
                    print("Complete frame (hex):", hexData)
                end
            end
        else
            -- 超时处理
           -- print("No data received within 1000ms")
        end
    end
end)

**Comment by S4FR** [comment]
> 遇到了相同的问题。我好像不少脚本都会遇到，就是时间一长就会有，我有一个查询的很快的脚本，就会遇到的非常频繁。
> 
> 报错如下：
> 
> [15:29:32:3125][I]-[sys] core loaded! [15:29:33:8118]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:29:40:7615]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:29:43:5231]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:29:58:1494]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:01:7588]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:02:9473]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:13:9054]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:22:5202]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger()
> 
> 我的LUA脚本如下：
> 
> local captureArray = { "\x60\x40", -- 帧头，例如55和A7 }
> 
> -- 注册串口接收函数 apiSetCb("uart", function (data) sys.publish("UART", data) -- 发布消息 end)
> 
> -- 将字符串转换为十六进制表示 local function toHex(str) return (str:gsub('.', function (c) return string.format('%02X ', string.byte(c)) end)) end
> 
> -- 获取当前时间戳 local function getTime() return os.date("%Y-%m-%d %H:%M:%S") end
> 
> -- 新建任务，等待接收到消息再继续运行 sys.taskInit(function() while true do -- 等待消息，超时1000ms local _, data = sys.waitUntil("UART", 1000) if data then local timestamp = getTime() local hexData = toHex(data)
> 
> ```
>         -- 遍历捕捉数组
>         for _, captureStr in ipairs(captureArray) do
>             -- 在接收到的数据中查找完全匹配的字符串
>             local matchPos = data:find(captureStr, 1, true)
>             if matchPos then
>                 local capturedData = data:sub(matchPos, matchPos + #captureStr - 1)
>                 print("Timestamp:", timestamp)
>                 print("Matched data (hex):", toHex(capturedData))
>                 print("Matched at position:", matchPos)
>                 print("Complete frame (hex):", hexData)
>             end
>         end
>     else
>         -- 超时处理
>        -- print("No data received within 1000ms")
>     end
> end
> ```
> 
> end)



> 遇到了相同的问题。我好像不少脚本都会遇到，就是时间一长就会有，我有一个查询的很快的脚本，就会遇到的非常频繁。
> 
> 报错如下：
> 
> [15:29:32:3125][I]-[sys] core loaded! [15:29:33:8118]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:29:40:7615]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:29:43:5231]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:29:58:1494]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:01:7588]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:02:9473]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:13:9054]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger() [15:30:22:5202]回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。 在 llcom.LuaEnv.LuaRunEnv.runTigger()
> 
> 我的LUA脚本如下：
> 
> local captureArray = { "\x60\x40", -- 帧头，例如55和A7 }
> 
> -- 注册串口接收函数 apiSetCb("uart", function (data) sys.publish("UART", data) -- 发布消息 end)
> 
> -- 将字符串转换为十六进制表示 local function toHex(str) return (str:gsub('.', function (c) return string.format('%02X ', string.byte(c)) end)) end
> 
> -- 获取当前时间戳 local function getTime() return os.date("%Y-%m-%d %H:%M:%S") end
> 
> -- 新建任务，等待接收到消息再继续运行 sys.taskInit(function() while true do -- 等待消息，超时1000ms local _, data = sys.waitUntil("UART", 1000) if data then local timestamp = getTime() local hexData = toHex(data)
> 
> ```
>         -- 遍历捕捉数组
>         for _, captureStr in ipairs(captureArray) do
>             -- 在接收到的数据中查找完全匹配的字符串
>             local matchPos = data:find(captureStr, 1, true)
>             if matchPos then
>                 local capturedData = data:sub(matchPos, matchPos + #captureStr - 1)
>                 print("Timestamp:", timestamp)
>                 print("Matched data (hex):", toHex(capturedData))
>                 print("Matched at position:", matchPos)
>                 print("Complete frame (hex):", hexData)
>             end
>         end
>     else
>         -- 超时处理
>        -- print("No data received within 1000ms")
>     end
> end
> ```
> 
> end)

版本也是1.1.3.3

**Comment by S4FR** [comment]
可能是多线程竞争问题。只勾选一个处理器的话就不会报错了。
![image](https://github.com/chenxuuu/llcom/assets/57590258/c3503ffa-0985-48e9-8dd0-fd43b754fc33)
![image](https://github.com/chenxuuu/llcom/assets/57590258/e8898e8f-d50a-49d9-b71a-52b9197e759c)

**Comment by chenxuuu** [comment]
xlua的bug，暂时没法修，很难搞

限制在某个特定cpu核心执行的话，感觉会影响程序性能？

**Comment by chenxuuu** [comment]
虽然不知道原因，但是可以试试看，看看我小改的这份还会不会出现这种问题？
[llcom.zip](https://github.com/user-attachments/files/15525148/llcom.zip)

**Comment by S4FR** [comment]
可以去xlua那边提个issue🤣

**Comment by chenxuuu** [comment]
xlua本身是有多线程支持的，可以先试试楼上我发的那个版本，我编译的xlua



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月4日(周二) 下午2:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenxuuu/llcom] 回调报错： System.NullReferenceException: 未将对象引用设置到对象的实例。    在 llcom.LuaEnv.LuaRunEnv.runTigger() (Issue #165)




 
可以去xlua那边提个issue🤣

**Comment by S4FR** [comment]
感谢大大抽空帮助！新编译的程序还是会出现这个bug，但是貌似频率变低了？没有仔细测试出现的概率。
复现的关键在于串口接收，
我测的时候如果串口从来不收东西是暂时没观察到这个问题出现的。有数据回送时候，比如把串口工具的TX接到RX上发啥收啥，就会容易复现这个问题。另外，限制CPU单个核心运行其实也会报这个错，但是概率会大大降低，我挂了一天出了几次，如果全部核心运行可能会十几秒出一次。

**Comment by chenxuuu** [comment]
还是等2.0版本吧，llcom-next会换用nlua，xlua这个问题已经很久了

**Comment by chenxuuu** [comment]
这bug快两年了，一直没有找到原因，基本只能把锅给到xlua了
但是单独写个demo又不能复现，反正就是很神奇

**Comment by chenxuuu** [comment]
[llcom.zip](https://github.com/user-attachments/files/15950539/llcom.zip)

试试这个还会出现报错吗

**Comment by chenxuuu** [comment]
[llcom.zip](https://github.com/user-attachments/files/15950590/llcom.zip)
然后这是另一个方案

目前我这里复现不了，各位可以帮忙测试下，看看这两个版本的效果是什么样的

**Comment by chenxuuu** [comment]
[llcom.zip](https://github.com/user-attachments/files/15963771/llcom.zip)

我觉得这样改应该就不会有问题了
