### ISSUE TITLE
发送数据无反应

### ISSUE THREAD

**Issue by RYLF** [chenxuuu/llcom#17]
**描述一下这个bug / Describe the bug**
请使用简介并详细的语句，来描述这个bug。 / A clear and concise description of what the bug is.
打开串口后发送数据无反应

**复现步骤 / To Reproduce**
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:

**预期的行为 / Expected behavior**
清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.

**截图 / Screenshots**
如果需要，请放上你的截图。 / If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/28991981/78850365-9fc65d00-7a49-11ea-9ba2-22e08d2ba617.png)

**日志 / Logs**
有，请上传日志为附件 / Upload your log files.

**系统信息 / Desktop (please complete the following information):**
win7 64

**其他备注信息 / Additional context**

**Comment by RYLF** [comment]
刚看了下，你这个软件好像是win7 64位不兼容哦。

**Comment by chenxuuu** [comment]
每天都再win7上测的，怎么可能不行

**Comment by RYLF** [comment]
> 每天都再win7上测的，怎么可能不行

那是什么原因呢。用SSCOM是可以的，用这个工具不行。

**Comment by RYLF** [comment]
> 每天都再win7上测的，怎么可能不行

![image](https://user-images.githubusercontent.com/28991981/78953283-ea5bde00-7b0a-11ea-9189-51771d83ebb6.png)

**Comment by chenxuuu** [comment]
你能复现的话，能帮我测试吗？

**Comment by RYLF** [comment]
> 你能复现的话，能帮我测试吗？

可以的，具体需要怎么测试。我的QQ：2461013399

**Comment by chenxuuu** [comment]
@all-contributors please add @RYLF for bug

**Comment by mikejzhiyu** [comment]
试试：发送的内容 加一下回车换行
