### ISSUE TITLE
关于快捷发送的“添加新项目”和“删除最后一项”按钮的优化建议

### ISSUE THREAD

**Issue by mt6595** [chenxuuu/llcom#175]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

当一次性需要增加很多快捷发送列表时，需要点击"添加新项目"按钮，然后滚轮滑一下，再点击"添加新项目"按钮，然后滚轮滑一下，再点击"添加新项目"按钮，然后滚轮滑一下......

### 描述您想要的解决方案 / Describe the solution you'd like

添加新项目和删除最后一项按钮点击时，滚动条保持在最下边

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

增加按钮点击执行代码
QuickScrollViewer.ScrollToVerticalOffset(QuickScrollViewer.ScrollableHeight);

**Comment by chenxuuu** [comment]
可以先用快照版了
