### ISSUE TITLE
能否增加“加回车换行”功能

### ISSUE THREAD

**Issue by mikejzhiyu** [chenxuuu/llcom#19]
需要自动增加回车换行的功能，能否支持一下

**Comment by chenxuuu** [comment]
工具自带了这个脚本的

更多设置 --> 对发送数据处理的Lua脚本 --> 脚本换成自带的那个**加上换行回车**

![图片](https://user-images.githubusercontent.com/10357394/79411175-c863cf00-7fd4-11ea-8b41-ecacd1d56e5e.png)

如果解决的话，点一下close

**Comment by mikejzhiyu** [comment]
感谢回复。可以解决。
我用的是“快捷发送列表”的功能，误以为“加上换行回车”仅对Lua脚本有效。
