### ISSUE TITLE
希望能解析air202/air800的调试串口日志

### ISSUE THREAD

**Issue by wendal** [chenxuuu/llcom#2]
**您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.**

**描述您想要的解决方案 / Describe the solution you'd like**

**描述您考虑过的替代方案 / Describe alternatives you've considered**

**其他备注信息**

**Comment by chenxuuu** [comment]
这个有啥意义？
实现能看日志，是不是还要加个下载烧录功能啊，有luatools的嘛

**Comment by whc2001** [comment]
世界上有无数种串口设备（虽然作者看起来是按照合宙的API设计的），因此除非某个功能十分常用或请求人数很多，否则不可能为每一种都提供支持。
/* 个人觉得这种针对性比较强的功能做成插件比较合适，LLCOM增加多个Lua脚本后台异步执行以及允许Lua脚本通过API生成WPF窗体并增加控件，然后就可以用Lua写各种插件了。作者看起来做到目前这个状态就基本结束了，我个人对WPF不是很熟悉，如果有机会的话可能会看看怎么搞 */
