### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Nigh** [chenxuuu/llcom#20]
**描述一下这个bug / Describe the bug**
使用附件中的setting文件无法正常启动。
[settings - 无法启动.zip](https://github.com/chenxuuu/llcom/files/4693079/settings.-.zip)

**复现步骤 / To Reproduce**
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:
如上描述。

**系统信息 / Desktop (please complete the following information):**
 - OS: Win 10 pro 1903

**其他备注信息 / Additional context**
疑为json解析或是封装存在问题。上一次的正常配置文件也没有正常读取。并且使用上一次的配置文件时，无法扫描到脚本目录的脚本。

**Comment by chenxuuu** [comment]
快速发送数据那边有问题导致解析失败崩了
