### ISSUE TITLE
建议增加“自动增加回车换行“的功能，有些设备接收信息以回车换行结尾

### ISSUE THREAD

**Issue by wanglianm** [chenxuuu/llcom#24]
**您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.**

**描述您想要的解决方案 / Describe the solution you'd like**

**描述您考虑过的替代方案 / Describe alternatives you've considered**

**其他备注信息**

**Comment by chenxuuu** [comment]
![图片](https://user-images.githubusercontent.com/10357394/105438807-a94e4800-5c9e-11eb-95b0-c78e07a4f818.png)
