### ISSUE TITLE
能否点击“刷新脚本列表”的时候改成加载硬盘上新版本，VSCode编辑的都被恢复掉了

### ISSUE THREAD

**Issue by zenghui** [chenxuuu/llcom#25]
# 如果不按该格式填写，开发者可能会直接忽略该issue

**您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.**

**描述您想要的解决方案 / Describe the solution you'd like**

**描述您考虑过的替代方案 / Describe alternatives you've considered**

**其他备注信息**

**Comment by chenxuuu** [comment]
https://github.com/chenxuuu/llcom/blob/master/llcom/DefaultFiles/user_script_run/example.lua#L1
