### ISSUE TITLE
脚本输出内容到文件

### ISSUE THREAD

**Issue by stupidtongtong** [chenxuuu/llcom#28]
调试某些产品时通常需要整晚运行，第二天再查看日志。希望脚本输出内容可以保存到文件中，方便调试。

**Comment by chenxuuu** [comment]
![图片](https://user-images.githubusercontent.com/10357394/125740076-39a5cebd-70ce-4f37-9126-fd16a690a4de.png)

点击，你会发现一个log文件夹，里面都是lua脚本的日志

**Comment by stupidtongtong** [comment]
哈哈，之前只发现了报文日志，没发现脚本日志，谢谢了。
