### ISSUE TITLE
希望代码界面可以有线条和折叠

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#31]
近期发现了这个软件并尝试使用,感觉很方便

正好经常写串口类的lua程序,就希望可以先在工具中跑通代码后再移植到开发板中

少量的代码测试没什么问题,但是如果代码长度过长,if开头,对应的结尾不好寻找

希望可以有个折叠,还有线条做个指示,这样就很方便了

最后祝程序越来越完善,感谢免费分享

**Comment by chenxuuu** [comment]
@all-contributors please add @wanglong126 for ideas
