### ISSUE TITLE
打开串口出错不响应

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#36]
某个串口设备出现问题,LLCOM点击打开串口无任何回应
其它工具打开会提示打开失败

但是当我将串口线断开,LLCOM会立即给出弹窗提示

但是并不是提示一次

点过多少次会弹出多少个弹窗,像这样
![Uploading 微信截图_20211201102004.png…]()

**Comment by chenxuuu** [comment]
无可靠复现方法
