### ISSUE TITLE
程序启动会抖动一下

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#37]
程序如果改变了位置和窗口尺寸
下次运行时会先在屏幕中间默认尺寸展示
紧接着会马上改变位置和尺寸到上次的地方,会抖动
可以先隐藏窗口,处理完成后再进行展示

**Comment by chenxuuu** [comment]
各有各的喜好

有些人想双击打开就立刻看见窗口。。。

**Comment by wanglong126** [comment]
如果打开能很快,又不抖动那就更好了.
撒花,结帖
