### ISSUE TITLE
增加注释快捷键

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#38]
代码区没有提示
可以按TAB和SHIFT TAB来调整格式
但是不能用SHIFT /来增加注释和取消注释
这个应该挺实用的

**Comment by chenxuuu** [comment]
代码编辑器区域不打算再加新功能了，一般来说复杂代码都会用其他编辑器进行编辑，工具自带的编辑器只考虑基础高亮功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月4日(周六) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 增加注释快捷键 (Issue #38)




 
代码区没有提示
 可以按TAB和SHIFT TAB来调整格式
 但是不能用SHIFT /来增加注释和取消注释
 这个应该挺实用的

**Comment by wanglong126** [comment]
嗯,这样也是可以的,但现在使用外部编辑器和llcom的代码不同步,外部更改的llcom不会变,但是llcom更改的会覆盖掉外部的编辑器
我看到提示说尽可能代码用require引入,但实际使用的时候,我是将常用的lua脚本引入,实际开发的少量代码是在代码编辑区

最近在玩screeps,这个游戏的代码编辑区和vscode是同步的,两个地方无论修改哪一方,都会更新,我觉得这样很好

**Comment by wanglong126** [comment]
git推送太痛苦了,附一下我的解决方法,

![image](https://user-images.githubusercontent.com/13432299/144780267-960d1176-4424-43a3-b0be-6f42bbd82509.png)

```c#
        Activated="Window_Activated"
        Deactivated="Window_Deactivated"
```

![image](https://user-images.githubusercontent.com/13432299/144780303-7549ea14-eb3a-43cf-9449-c42ba933c34f.png)

```c#
        //最后打开文件的时间
        private static DateTime lastLuaFileTime = DateTime.Now;
```

![image](https://user-images.githubusercontent.com/13432299/144780372-d5612f10-e4f6-4106-a376-0f3c665eb267.png)

```c#
            //记录最后时间
            lastLuaFileTime = File.GetLastWriteTime(Tools.Global.ProfilePath + $"user_script_run/{Tools.Global.setting.runScript}.lua");
```
和
```c#
                //记录最后时间
                lastLuaFileTime = File.GetLastWriteTime(Tools.Global.ProfilePath + $"user_script_run/{fileName}.lua");
```


![image](https://user-images.githubusercontent.com/13432299/144780436-8180ec33-eb9b-4208-a6e3-0b477096c302.png)


```C#
        private void Window_Deactivated(object sender, EventArgs e)
        {
            //窗口变为后台,可能在切换编辑器,自动保存脚本
            if (lastLuaFile != "")
                saveLuaFile(lastLuaFile);
        }
        private void Window_Activated(object sender, EventArgs e)
        {
            if (lastLuaFile != "")
            {
                //当前文件最后时间
                DateTime fileTime = File.GetLastWriteTime(Tools.Global.ProfilePath + $"user_script_run/{lastLuaFile}.lua");
                if (fileTime > lastLuaFileTime)//代码在外部被修改
                {
                    loadLuaFile(lastLuaFile);
                }
            }
        }
```

**Comment by chenxuuu** [comment]
GitHub连不上的话，其实码云也有镜像，可以pr到那里
https://gitee.com/chenxuuu/llcom

**Comment by chenxuuu** [comment]
@all-contributors please add @wanglong126 for bug, ideas and code

**Comment by wanglong126** [comment]
> GitHub连不上的话，其实码云也有镜像，可以pr到那里 https://gitee.com/chenxuuu/llcom

不太熟练git类平台,在gitee上显示无权fok,就不太会如何操作了

**Comment by chenxuuu** [comment]
@wanglong126 能fork了

**Comment by wanglong126** [comment]
> @wanglong126 能fork了

试着提交了两个,也不知道对不对
