### ISSUE TITLE
运行lua代码时闪退

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#41]
在测试lua代码时遇到窗口闪退
用源码在vs调试情况下运行lua代码
捕获到错误如下
![image](https://user-images.githubusercontent.com/13432299/145315722-045c0375-8b9e-4167-a68d-c44b00a77a81.png)

![image](https://user-images.githubusercontent.com/13432299/145315747-94b52151-0d92-4c8f-bfc2-f5039da06311.png)

然后程序会消失

**Comment by chenxuuu** [comment]
复现方法？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月9日(周四) 上午9:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 运行lua代码时闪退 (Issue #41)




 
在测试lua代码时遇到窗口闪退
 用源码在vs调试情况下运行lua代码
 捕获到错误如下
 
 

 
然后程序会消失

**Comment by wanglong126** [comment]
我现在的能百分百的重现这个错误,但是比较麻烦,我再测试一会儿,看看能不能提供个简单的复现方法

**Comment by wanglong126** [comment]
我缩减了一下代码,加你QQ发给你吧
