### ISSUE TITLE
打印时间戳功能需要一个 开启/关闭 开关

### ISSUE THREAD

**Issue by fylsle** [chenxuuu/llcom#42]
# 如果不按该格式填写，开发者可能会直接忽略该issue

**您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.**

很多时候，并不关心时间戳的问题，而此时输出窗口的时间戳反而显得有些多余

**描述您想要的解决方案 / Describe the solution you'd like**

给输出窗口加一个 时间戳的开关

**描述您考虑过的替代方案 / Describe alternatives you've considered**

**其他备注信息**

**Comment by chenxuuu** [comment]
分包时间改成负数就不分包了
