### ISSUE TITLE
首先感谢您 一款非常好的软件; 是否也可以给出一个 脚本调用 MQTT 的Demo  其实很重要呀

### ISSUE THREAD

**Issue by yudehe2009** [chenxuuu/llcom#45]
# 如果不按该格式填写，开发者可能会直接忽略该issue

**您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.**

**描述您想要的解决方案 / Describe the solution you'd like**

**描述您考虑过的替代方案 / Describe alternatives you've considered**

**其他备注信息**

**Comment by yudehe2009** [comment]
非常好的一款软件  建议给出 脚本调用MQTT 协议的DEMO

**Comment by chenxuuu** [comment]
目前没有给lua提供mqtt接口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 上午8:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [chenxuuu/llcom] 首先感谢您 一款非常好的软件; 是否也可以给出一个 脚本调用 MQTT 的Demo  其实很重要呀 (Issue #45)




 
非常好的一款软件  建议给出 脚本调用MQTT 协议的DEMO

**Comment by yudehe2009** [comment]
感谢您百忙之中的回复 顺颂时祺！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 上午9:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chenxuuu/llcom] 首先感谢您 一款非常好的软件; 是否也可以给出一个 脚本调用 MQTT 的Demo  其实很重要呀 (Issue #45)




 目前没有给lua提供mqtt接口 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年4月12日(周二) 上午8:39 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: Re: [chenxuuu/llcom] 首先感谢您 一款非常好的软件; 是否也可以给出一个 脚本调用 MQTT 的Demo  其实很重要呀 (Issue #45) 
 
 
 
 
   
 非常好的一款软件  建议给出 脚本调用MQTT 协议的DEMO
