### ISSUE TITLE
接收串口数据12-24小时后会卡，打印窗口滚轮会莫名其妙慢慢往上移，鼠标点击关闭串口会没反应。

### ISSUE THREAD

**Issue by mahuagithub** [chenxuuu/llcom#46]
# 如果不按该格式填写，开发者可能会直接忽略该issue

**描述一下这个bug / Describe the bug**
请使用简介并详细的语句，来描述这个bug。 / A clear and concise description of what the bug is.

**复现步骤 / To Reproduce**
按照下面的步骤，可以复现bug / Steps to reproduce the behavior:

**预期的行为 / Expected behavior**
清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.

**截图 / Screenshots**
如果需要，请放上你的截图。 / If applicable, add screenshots to help explain your problem.

**日志 / Logs**
有，请上传日志为附件 / Upload your log files.

**系统信息 / Desktop (please complete the following information):**

**其他备注信息 / Additional context**

**Comment by chenxuuu** [comment]
清空串口数据即可
