### ISSUE TITLE
未知原因，功能异常，关闭主界面，后台程序一直在运行，无法正常再次运行程序

### ISSUE THREAD

**Issue by fylsle** [chenxuuu/llcom#47]
未知原因，功能异常，关闭主界面，后台程序一直在运行，无法正常再次运行程序
![image](https://user-images.githubusercontent.com/35376614/165675170-4cbdae41-acba-48cb-b3a9-123f0cf5ebce.png)

<img width="273" alt="image" src="https://user-images.githubusercontent.com/35376614/165674780-d65b0e97-4571-4671-90d5-3e924ff85b76.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/35376614/165674897-8dcb26c4-adaa-4b7a-a328-2e5292190c7a.png">

[log20220428.txt](https://github.com/chenxuuu/llcom/files/8579450/log20220428.txt)

**Comment by chenxuuu** [comment]
请按格式描述，不然此issue将关闭



---原始邮件---
发件人: "Alex ***@***.***&gt;
发送时间: 2022年4月28日(周四) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [chenxuuu/llcom] 未知原因，功能异常，关闭主界面，后台程序一直在运行，无法正常再次运行程序 (Issue #47)




 
未知原因，功能异常，关闭主界面，后台程序一直在运行，无法正常再次运行程序
 
 

 

 
log20220428.txt

**Comment by chenxuuu** [comment]
信息不足
