### ISSUE TITLE
建议增加一个tcp的功能

### ISSUE THREAD

**Issue by Layty** [chenxuuu/llcom#48]
建议抽象 通道为 tcp/udp/串口,类似sscom那样

**Comment by chenxuuu** [comment]
现在有tcp服务端/客户端了，你这个需求详细说说？

**Comment by Layty** [comment]
我是想在串口那个位置使用 tcp/udp  和sscom那种使用,这样 socket 也可以使用 发送列表
然后  lua脚本里只需要  local r,udata = sys.waitUntil("channal",1000)      这里的  channal 为通用型的接口,即当前选择了什么类型的硬件,实际发送的是什么,即lua脚本不关心/或者说可以不知道 是tcp 还是 uart
