### ISSUE TITLE
运行lua脚本的代码,不要自动保存

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#54]
推荐他人使用llcom进行调试

使用外部编辑器luaStudio进行代码的编辑,在llcom运行脚本

每次回到luaStudio编辑器都会提示代码外部更新

如果代码编辑地方不打算做优化的话,是否可以在设置中增加一个选项

类似于ArduinoIde中的使用外部编辑器选项

勾选了这个选项后,在编辑界面代码时只读的,会加载不会再覆盖了

**Comment by chenxuuu** [comment]
已有此功能：https://github.com/chenxuuu/llcom/commit/b714d44973499484f3467a6b6866b333e671ef44

例子代码注释没有改，你可以帮忙改一下😺

**Comment by wanglong126** [comment]
嗯...不太对,上次做的是外部修改了,llcom要加载,现在碰到的问题是llcom总覆盖外部修改的结果,我看下原因,等下再来回复

**Comment by wanglong126** [comment]
看了下是每次编辑器失去焦点和窗口切后台,都会写一次文件,写文件时没做判断,我试试改动下

**Comment by wanglong126** [comment]
提交了个PR #55 
这样之后好多了,外部编辑器不会一直提示文件被修改需要重新加载了

**Comment by chenxuuu** [comment]
合并了，感谢

**Comment by wanglong126** [comment]
客气喽,啥时候发版呢
