### ISSUE TITLE
运行lua脚本特定选项会消失

### ISSUE THREAD

**Issue by wanglong126** [chenxuuu/llcom#57]
很奇怪的现象,能百分百复现,但暂时不知道引起原因

先记录下

![某个选项会空白](https://user-images.githubusercontent.com/13432299/180153962-a048f740-cbf8-4c75-9c7b-799f70378c8b.gif)

**Comment by chenxuuu** [comment]
这是ui库的bug，我也不知道复现原因，可以研究一下去那边提个issue？

**Comment by chenxuuu** [comment]
https://github.com/benruehl/adonis-ui

**Comment by chenxuuu** [comment]
https://github.com/chenxuuu/llcom/commit/7a4a2e053dcd873d0a4a2026fb5cebdb2c94caae

当时改文件名就是因为遇到了这个bug

**Comment by wanglong126** [comment]
这个确实好奇怪,在我这台电脑上其他的都没问题就选这个会出问题,如果后续找到原因了,我在这里备注下,等下我再测试测试看看

**Comment by chenxuuu** [comment]
再不行就换个ui框架嘛，反正完全没用到框架特性，去掉ui也能正常跑

**Comment by wanglong126** [comment]
先看看吧,这个现象挺奇怪的

**Comment by wanglong126** [comment]
#58 你验证下看看,我这边测试可以了

**Comment by chenxuuu** [comment]
感谢修复
