### ISSUE TITLE
数据显示这个设置位置建议

### ISSUE THREAD

**Issue by linhongz** [chenxuuu/llcom#59]
数据显示HEX还是文本数据这个选项可以考虑放到外面吗，因为这个选项用到的频率比较高。同时显示两者的话，如果是hex数据那么文本数据就有可能是乱码的，对于强迫症患者来说非常难受。

**Comment by chenxuuu** [comment]
没有看懂

**Comment by linhongz** [comment]
![This is an image2](https://m.360buyimg.com/babel/jfs/t1/208095/5/25118/27413/62e0d362Ebfa69609/a86142a2bcdc86b8.png)
![This is an image](https://m.360buyimg.com/babel/jfs/t1/188254/20/27283/85881/62e0d362Eb491b7a9/1a9bd6e22ef63357.png)

**就是上面那个图一框起来的部分能不能放到图二那里**

**Comment by chenxuuu** [comment]
请按issue模板填写
