### ISSUE TITLE
希望增加hex发送选项

### ISSUE THREAD

**Issue by linhongz** [chenxuuu/llcom#61]
目前在右侧快捷发送区域可以选择hex模式发送，但是在主发送区域没有这个功能，只能发送文本数据，希望可以增加一个选项

**Comment by chenxuuu** [comment]
![图片](https://user-images.githubusercontent.com/10357394/181487705-80e70f2c-a26d-48aa-8571-61a689ee6e0e.png)

？

**Comment by linhongz** [comment]
不是显示选项，是发送选项。发送hex数据，目前的版本是在右侧快捷内容有这个选项，但是底部主发送区域没有

**Comment by chenxuuu** [comment]
https://github.com/chenxuuu/llcom/commit/c9b2072d73b1ef5c86d55fc72de951fadeefa9b3
