### ISSUE TITLE
英文版系统运行会发生错误

### ISSUE THREAD

**Issue by panyonglin** [chenxuuu/llcom#68]
**描述一下这个bug / Describe the bug**
1. 打开串口后，点击发送会出现文件未找到错误。
2. 收到数据也会出现错误

**截图 / Screenshots**
![image](https://user-images.githubusercontent.com/36882793/186619189-a386812f-0ca9-4dc9-a4bd-7dbda8f38391.png)

**Comment by chenxuuu** [comment]
新建一个发送脚本，使用英文命名
