### ISSUE TITLE
Lua通用通道功能

### ISSUE THREAD

**Issue by Layty** [chenxuuu/llcom#69]
https://github.com/chenxuuu/llcom/issues/48

我是想在串口那个位置使用 tcp/udp 和sscom那种使用,这样 socket 也可以使用 发送列表
然后 lua脚本里只需要 local r,udata = sys.waitUntil("channal",1000) 这里的 channal 为通用型的接口,即当前选择了什么类型的硬件,实际发送的是什么,即lua脚本不关心/或者说可以不知道 是tcp 还是 uart

**Comment by chenxuuu** [comment]
先设计一套接口的样式吧

目前串口的接收接口是`apiSendUartData`函数与`uartReceive`回调的形式，需要改一下

比如改成这样，channel可以用`mqtt`、`uart`、`tcp`等代替

```lua
apiSend(channel, data)
apiSetCb(channel, funcrion)
```

例子:

```lua
apiSetCb("mqtt", funcrion(d) print("recv from mqtt",d) end)
sys.timerLoopStart(apiSend,1000,"mqtt","test")
```

有什么建议吗

**Comment by Layty** [comment]
建议api文档增加下socket相关的

**Comment by chenxuuu** [comment]
着什么急，还没开工呢
