### ISSUE TITLE
加入简单绘制动态曲线功能

### ISSUE THREAD

**Issue by Dandjinh** [chenxuuu/llcom#7]
是否可以考虑加入一些动态曲线的api，实现弹出个框，绘制动态曲线的功能？

**Comment by chenxuuu** [comment]
给你个显示、绘制图片的接口？
还是指可以实时动态更改显示内容的接口？

**Comment by Dandjinh** [comment]
我本来想的是看可不可以把chart控件封装下

**Comment by chenxuuu** [comment]
@Dandjinh 这功能还要吗？具体想要啥效果
