### ISSUE TITLE
小工具/socket服务端，IP地址不能编辑

### ISSUE THREAD

**Issue by IC-killer** [chenxuuu/llcom#70]
![image](https://user-images.githubusercontent.com/56482204/188152564-8d371892-8acf-45b5-826a-4000ffebfb81.png)
socket服务端ip不能编辑

**Comment by chenxuuu** [comment]
服务端使用的为netlab.luatos.com与netlab.luatos.org，ip为服务器分配

**Comment by chenxuuu** [comment]
新版本可以开本地服务端了
