### ISSUE TITLE
apiQuickSendList(id)接口建议增加一个获取发送框文本的功能，非常感谢。

### ISSUE THREAD

**Issue by qnxsgwy** [chenxuuu/llcom#72]
当前apiQuickSendList(id)接口只能获取快捷发送列表内容，如果想临时循环发送发送框输入的内容，还需要额外创建一个快捷发送列表项，用完后再删除掉。
建议扩展当前的apiQuickSendList(id)接口，当id>0时表示需要获取的快捷发送区数据的序号，当id=0时表示获取当前发送框内的内容。

**Comment by chenxuuu** [comment]
没理解为什么不直接把数据放快捷发送列表里

**Comment by qnxsgwy** [comment]
> 没理解为什么不直接把数据放放列表快捷里

可以放进去，我现在就是这样用的，这不是想着如果直接可以直接调用发送框输入的内容，用起来会方便一点，大佬有空的时候可以考虑一下，能不能加上这功能。

**Comment by chenxuuu** [comment]
其实完全不用加，你直接用`CS.llcom.Tools.Global.setting.dataToSend`这个变量就行

**Comment by chenxuuu** [comment]
所以你可以直接加一句`apiToSend = function() return CS.llcom.Tools.Global.setting.dataToSend end`这种的东西，就能满足你的需求，完全不用改c#代码
