### ISSUE TITLE
希望MQTT支持证书链接方式

### ISSUE THREAD

**Issue by jinhe1314** [chenxuuu/llcom#99]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
希望MQTT支持证书链接方式
## 描述您想要的解决方案 / Describe the solution you'd like
类似MQTTX
## 描述您考虑过的替代方案 / Describe alternatives you've considered
无
## 其他备注信息
![image](https://user-images.githubusercontent.com/973213/215383938-f6db98df-ec29-4f3b-a919-1ad35fadfdfa.png)

**Comment by chenxuuu** [comment]
自选证书？没测试服务器，可以给个能测试的服务器和连接配置吗

**Comment by chenxuuu** [comment]
测试服务器：
https://www.emqx.com/zh/mqtt/public-mqtt5-broker

测试用的客户端证书：
[certificate.zip](https://github.com/chenxuuu/llcom/files/10661838/certificate.zip)
